common errors: semicolon after for, while
mrlvsb/upr-skripta pull request #30
Opened 2020-10-02 18:46 UTC by trnila

2020-10-02 19:18 UTC, Kobzol requested changes

2020-10-02 19:18 UTC, Kobzol commented on src/caste_chyby/caste_chyby.md
> +Středník za `for`, `while` nebo `if` by ve většině případů neměl být, protože se na jeho místě vytvoří prázdný blok kódu.
Navrhuji to přeformulovat následovně:
~~~
Příkazy `for`, `while` nebo `if` za svou uzavírací závorkou `)` očekávají jeden příkaz:
```c
if (a > b) printf("%d", a);
```
nebo blok s příkazy:
```c
if (a > b) {
    printf("%d", a);
    ...
}
```

Pokud však za závorku dáte za závorku středník (`;`), tak překladač to pochopí jako prázdný příkaz, který nic nedělá.
~~~

2020-10-02 19:18 UTC, Kobzol commented on src/caste_chyby/caste_chyby.md
> +Středník za `if` vytvoří prázdný blok kódu, takže anonymní blok kódu s příkazem `printf` se vždy vypíše i když je podmínka nesplnitelná.
Zde opět středník za `if` reprezentuje prázdný příkaz, takže blok kódu s příkazem `printf` se provede vždy, i když je tato podmínka nesplnitelná.

2020-10-02 19:18 UTC, Kobzol commented on src/caste_chyby/caste_chyby.md
> +
Je to ekvivalentní, jako byste napsali
```c
if (0) { /* zde není co provést */ }

// tento blok se provede vždy
{
    printf("Hello\n");
}
```

2020-10-05 13:55 UTC, trnila commented
to mi tam toho moc nezbylo :D ale diky! je to o hodne lepsi :)

2020-10-05 13:55 UTC, merged